; Auto-generated. Do not edit!


(cl:in-package Assg1-msg)


;//! \htmlinclude BakeCakeGoal.msg.html

(cl:defclass <BakeCakeGoal> (roslisp-msg-protocol:ros-message)
  ((num_cakes
    :reader num_cakes
    :initarg :num_cakes
    :type cl:integer
    :initform 0))
)

(cl:defclass BakeCakeGoal (<BakeCakeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BakeCakeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BakeCakeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name Assg1-msg:<BakeCakeGoal> is deprecated: use Assg1-msg:BakeCakeGoal instead.")))

(cl:ensure-generic-function 'num_cakes-val :lambda-list '(m))
(cl:defmethod num_cakes-val ((m <BakeCakeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader Assg1-msg:num_cakes-val is deprecated.  Use Assg1-msg:num_cakes instead.")
  (num_cakes m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BakeCakeGoal>) ostream)
  "Serializes a message object of type '<BakeCakeGoal>"
  (cl:let* ((signed (cl:slot-value msg 'num_cakes)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BakeCakeGoal>) istream)
  "Deserializes a message object of type '<BakeCakeGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num_cakes) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BakeCakeGoal>)))
  "Returns string type for a message object of type '<BakeCakeGoal>"
  "Assg1/BakeCakeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BakeCakeGoal)))
  "Returns string type for a message object of type 'BakeCakeGoal"
  "Assg1/BakeCakeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BakeCakeGoal>)))
  "Returns md5sum for a message object of type '<BakeCakeGoal>"
  "6d3e30b2ed75c520b8f2ca1010c57ae6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BakeCakeGoal)))
  "Returns md5sum for a message object of type 'BakeCakeGoal"
  "6d3e30b2ed75c520b8f2ca1010c57ae6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BakeCakeGoal>)))
  "Returns full string definition for message of type '<BakeCakeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 num_cakes~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BakeCakeGoal)))
  "Returns full string definition for message of type 'BakeCakeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 num_cakes~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BakeCakeGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BakeCakeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'BakeCakeGoal
    (cl:cons ':num_cakes (num_cakes msg))
))
