; Auto-generated. Do not edit!


(cl:in-package Assg1-msg)


;//! \htmlinclude BakeCakeResult.msg.html

(cl:defclass <BakeCakeResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:string
    :initform ""))
)

(cl:defclass BakeCakeResult (<BakeCakeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BakeCakeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BakeCakeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name Assg1-msg:<BakeCakeResult> is deprecated: use Assg1-msg:BakeCakeResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <BakeCakeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader Assg1-msg:result-val is deprecated.  Use Assg1-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BakeCakeResult>) ostream)
  "Serializes a message object of type '<BakeCakeResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'result))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BakeCakeResult>) istream)
  "Deserializes a message object of type '<BakeCakeResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'result) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BakeCakeResult>)))
  "Returns string type for a message object of type '<BakeCakeResult>"
  "Assg1/BakeCakeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BakeCakeResult)))
  "Returns string type for a message object of type 'BakeCakeResult"
  "Assg1/BakeCakeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BakeCakeResult>)))
  "Returns md5sum for a message object of type '<BakeCakeResult>"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BakeCakeResult)))
  "Returns md5sum for a message object of type 'BakeCakeResult"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BakeCakeResult>)))
  "Returns full string definition for message of type '<BakeCakeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BakeCakeResult)))
  "Returns full string definition for message of type 'BakeCakeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BakeCakeResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BakeCakeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BakeCakeResult
    (cl:cons ':result (result msg))
))
