(cl:defpackage lab3-msg
  (:use )
  (:export
   "<BAKECAKEACTION>"
   "BAKECAKEACTION"
   "<BAKECAKEACTIONFEEDBACK>"
   "BAKECAKEACTIONFEEDBACK"
   "<BAKECAKEACTIONGOAL>"
   "BAKECAKEACTIONGOAL"
   "<BAKECAKEACTIONRESULT>"
   "BAKECAKEACTIONRESULT"
   "<BAKECAKEFEEDBACK>"
   "BAKECAKEFEEDBACK"
   "<BAKECAKEGOAL>"
   "BAKECAKEGOAL"
   "<BAKECAKERESULT>"
   "BAKECAKERESULT"
  ))

