// Generated by gencpp from file Assg1/WishResponse.msg
// DO NOT EDIT!


#ifndef ASSG1_MESSAGE_WISHRESPONSE_H
#define ASSG1_MESSAGE_WISHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Assg1
{
template <class ContainerAllocator>
struct WishResponse_
{
  typedef WishResponse_<ContainerAllocator> Type;

  WishResponse_()
    : Birthday_wish()  {
    }
  WishResponse_(const ContainerAllocator& _alloc)
    : Birthday_wish(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Birthday_wish_type;
  _Birthday_wish_type Birthday_wish;





  typedef boost::shared_ptr< ::Assg1::WishResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Assg1::WishResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WishResponse_

typedef ::Assg1::WishResponse_<std::allocator<void> > WishResponse;

typedef boost::shared_ptr< ::Assg1::WishResponse > WishResponsePtr;
typedef boost::shared_ptr< ::Assg1::WishResponse const> WishResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Assg1::WishResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Assg1::WishResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Assg1::WishResponse_<ContainerAllocator1> & lhs, const ::Assg1::WishResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Birthday_wish == rhs.Birthday_wish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Assg1::WishResponse_<ContainerAllocator1> & lhs, const ::Assg1::WishResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Assg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Assg1::WishResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Assg1::WishResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Assg1::WishResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Assg1::WishResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Assg1::WishResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Assg1::WishResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Assg1::WishResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3831a1561f29ba6635afabb15f334d9";
  }

  static const char* value(const ::Assg1::WishResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3831a1561f29ba6ULL;
  static const uint64_t static_value2 = 0x635afabb15f334d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::Assg1::WishResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Assg1/WishResponse";
  }

  static const char* value(const ::Assg1::WishResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Assg1::WishResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Birthday_wish\n"
"\n"
;
  }

  static const char* value(const ::Assg1::WishResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Assg1::WishResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Birthday_wish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WishResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Assg1::WishResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Assg1::WishResponse_<ContainerAllocator>& v)
  {
    s << indent << "Birthday_wish: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Birthday_wish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSG1_MESSAGE_WISHRESPONSE_H
