// Generated by gencpp from file Assg1/Wish.msg
// DO NOT EDIT!


#ifndef ASSG1_MESSAGE_WISH_H
#define ASSG1_MESSAGE_WISH_H

#include <ros/service_traits.h>


#include <Assg1/WishRequest.h>
#include <Assg1/WishResponse.h>


namespace Assg1
{

struct Wish
{

typedef WishRequest Request;
typedef WishResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wish
} // namespace Assg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Assg1::Wish > {
  static const char* value()
  {
    return "17bec33fa207fbe940faaa035627acb2";
  }

  static const char* value(const ::Assg1::Wish&) { return value(); }
};

template<>
struct DataType< ::Assg1::Wish > {
  static const char* value()
  {
    return "Assg1/Wish";
  }

  static const char* value(const ::Assg1::Wish&) { return value(); }
};


// service_traits::MD5Sum< ::Assg1::WishRequest> should match
// service_traits::MD5Sum< ::Assg1::Wish >
template<>
struct MD5Sum< ::Assg1::WishRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Assg1::Wish >::value();
  }
  static const char* value(const ::Assg1::WishRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Assg1::WishRequest> should match
// service_traits::DataType< ::Assg1::Wish >
template<>
struct DataType< ::Assg1::WishRequest>
{
  static const char* value()
  {
    return DataType< ::Assg1::Wish >::value();
  }
  static const char* value(const ::Assg1::WishRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Assg1::WishResponse> should match
// service_traits::MD5Sum< ::Assg1::Wish >
template<>
struct MD5Sum< ::Assg1::WishResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Assg1::Wish >::value();
  }
  static const char* value(const ::Assg1::WishResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Assg1::WishResponse> should match
// service_traits::DataType< ::Assg1::Wish >
template<>
struct DataType< ::Assg1::WishResponse>
{
  static const char* value()
  {
    return DataType< ::Assg1::Wish >::value();
  }
  static const char* value(const ::Assg1::WishResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSG1_MESSAGE_WISH_H
