// Generated by gencpp from file lab3/BakeCakeResult.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_BAKECAKERESULT_H
#define LAB3_MESSAGE_BAKECAKERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab3
{
template <class ContainerAllocator>
struct BakeCakeResult_
{
  typedef BakeCakeResult_<ContainerAllocator> Type;

  BakeCakeResult_()
    : result()  {
    }
  BakeCakeResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::lab3::BakeCakeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab3::BakeCakeResult_<ContainerAllocator> const> ConstPtr;

}; // struct BakeCakeResult_

typedef ::lab3::BakeCakeResult_<std::allocator<void> > BakeCakeResult;

typedef boost::shared_ptr< ::lab3::BakeCakeResult > BakeCakeResultPtr;
typedef boost::shared_ptr< ::lab3::BakeCakeResult const> BakeCakeResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab3::BakeCakeResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab3::BakeCakeResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab3::BakeCakeResult_<ContainerAllocator1> & lhs, const ::lab3::BakeCakeResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab3::BakeCakeResult_<ContainerAllocator1> & lhs, const ::lab3::BakeCakeResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab3::BakeCakeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab3::BakeCakeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::BakeCakeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::BakeCakeResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::BakeCakeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::BakeCakeResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab3::BakeCakeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::lab3::BakeCakeResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::lab3::BakeCakeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab3/BakeCakeResult";
  }

  static const char* value(const ::lab3::BakeCakeResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab3::BakeCakeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string result\n"
;
  }

  static const char* value(const ::lab3::BakeCakeResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab3::BakeCakeResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BakeCakeResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab3::BakeCakeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab3::BakeCakeResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB3_MESSAGE_BAKECAKERESULT_H
