// Generated by gencpp from file lab3/BakeCakeGoal.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_BAKECAKEGOAL_H
#define LAB3_MESSAGE_BAKECAKEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab3
{
template <class ContainerAllocator>
struct BakeCakeGoal_
{
  typedef BakeCakeGoal_<ContainerAllocator> Type;

  BakeCakeGoal_()
    : num_cakes(0)  {
    }
  BakeCakeGoal_(const ContainerAllocator& _alloc)
    : num_cakes(0)  {
  (void)_alloc;
    }



   typedef int64_t _num_cakes_type;
  _num_cakes_type num_cakes;





  typedef boost::shared_ptr< ::lab3::BakeCakeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab3::BakeCakeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct BakeCakeGoal_

typedef ::lab3::BakeCakeGoal_<std::allocator<void> > BakeCakeGoal;

typedef boost::shared_ptr< ::lab3::BakeCakeGoal > BakeCakeGoalPtr;
typedef boost::shared_ptr< ::lab3::BakeCakeGoal const> BakeCakeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab3::BakeCakeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab3::BakeCakeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab3::BakeCakeGoal_<ContainerAllocator1> & lhs, const ::lab3::BakeCakeGoal_<ContainerAllocator2> & rhs)
{
  return lhs.num_cakes == rhs.num_cakes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab3::BakeCakeGoal_<ContainerAllocator1> & lhs, const ::lab3::BakeCakeGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab3::BakeCakeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab3::BakeCakeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::BakeCakeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::BakeCakeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::BakeCakeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::BakeCakeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab3::BakeCakeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d3e30b2ed75c520b8f2ca1010c57ae6";
  }

  static const char* value(const ::lab3::BakeCakeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d3e30b2ed75c520ULL;
  static const uint64_t static_value2 = 0xb8f2ca1010c57ae6ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab3::BakeCakeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab3/BakeCakeGoal";
  }

  static const char* value(const ::lab3::BakeCakeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab3::BakeCakeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 num_cakes\n"
;
  }

  static const char* value(const ::lab3::BakeCakeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab3::BakeCakeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_cakes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BakeCakeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab3::BakeCakeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab3::BakeCakeGoal_<ContainerAllocator>& v)
  {
    s << indent << "num_cakes: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num_cakes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB3_MESSAGE_BAKECAKEGOAL_H
